<a href="https://colab.research.google.com/github/msatya7045/week4_python/blob/main/Satyajit_Week4_Evaluation_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Display Powers of 2 Using Anonymous Function**

**2. Find Factorial of Number Using Recursion**

**3. Add Two Matrices**

**4. print the second largest element in an array**

**5. sort the elements of an array in descending order**

**6. Counts the Number of Times a Letter Appears in the Text File**

**7. Extract Numbers from Text File**

In [161]:
#1. Display Powers of 2 Using Anonymous
input_number = int(input('input number :'))
power = lambda a: a*a
power(input_number)

input number :2


4

In [162]:
#2. Find Factorial of Number Using Recursion


number= int(input('Input number :'))

if number>0:

  fact = 1

  for i in range(1,number+1):
    fact = fact * i
  print('factorial of',number,"is",fact)
elif number == 0:
  fact = 1
  print('factorial of',number,"is",fact)
else:
  print("factorial can't defind")



Input number :5
factorial of 5 is 120


In [163]:

def fact_of_number(number):

  if number>0:

    fact = 1

    for i in range(1,number+1):
      fact = fact * i
    return ('factorial of',number,"is",fact)
  elif number == 0:
    fact = 1
    return ('factorial of',number,"is",fact)
  else:
    return ("factorial can't defind")

In [164]:
fact_of_number(-1)

"factorial can't defind"

In [165]:
#factorial using recurssion

def fact_recurssion(number):
  if number==1:
    return number
  elif number<0:
    return 'number is -ve factorial can nt defined'
  elif number==0:
    return 1
  else:
    return number * fact_recurssion(number-1)


In [166]:
fact_recurssion(0)

1

In [167]:
#3. Add Two Matrices

import numpy as np


a = np.random.randint(10, size=(3, 3))
b= np.random.randint(10, size=(3, 3))
print(a)
print(b)


addition_of_ab = a+b
addition_of_ab







[[1 2 1]
 [9 7 7]
 [5 1 5]]
[[7 2 3]
 [0 2 7]
 [3 2 5]]


array([[ 8,  4,  4],
       [ 9,  9, 14],
       [ 8,  3, 10]])

In [168]:
#4. print the second largest element in an array

a = [1,2,3,4,4,5,40,30,10]
b= np.array(a)
sorted_b = sorted(b)
secound_largest = sorted_b[-2]
secound_largest

30

In [169]:
#5. sort the elements of an array in descending order
a = [1,2,3,4,4,5,40,30,10]
b= np.array(a)

sorted_b = sorted(b,reverse = True)
sorted_b



[40, 30, 10, 5, 4, 4, 3, 2, 1]


**6. Counts the Number of Times a Letter Appears in the Text File**

In [170]:
a = open('random_text.txt')

In [171]:
data = a.read()
data

"Last weekend, we decided to explore the picturesque park nearby. The park's lush beauty immediately captivated us with its tall, majestic trees and vibrant green grass. Excitement filled the air as we embarked on our leisurely stroll along the winding pathways, eager to uncover the park's hidden treasures.\n\nAs we meandered, we spotted adorable squirrels frolicking playfully among the branches, their bushy tails adding to the charm of the scene. Mesmerized, we paused to admire their antics, cherishing the tranquility of the moment.\n\nSeeking respite, we settled on a weathered wooden bench beneath the shade of a sprawling oak. A gentle breeze rustled the leaves, soothing us while we immersed ourselves in the peaceful ambiance. Nature's embrace was refreshing, rejuvenating our spirits.\n\nSoon, our journey resumed, and we encountered a cheerful group of kids engaged in a lively game of frisbee. Their laughter filled the air with infectious joy, and we couldn't help but smile at their 

In [172]:
list_text = data.replace('\n'," ")

list_text2= list_text.split(" ")



In [173]:
print(list_text2)


['Last', 'weekend,', 'we', 'decided', 'to', 'explore', 'the', 'picturesque', 'park', 'nearby.', 'The', "park's", 'lush', 'beauty', 'immediately', 'captivated', 'us', 'with', 'its', 'tall,', 'majestic', 'trees', 'and', 'vibrant', 'green', 'grass.', 'Excitement', 'filled', 'the', 'air', 'as', 'we', 'embarked', 'on', 'our', 'leisurely', 'stroll', 'along', 'the', 'winding', 'pathways,', 'eager', 'to', 'uncover', 'the', "park's", 'hidden', 'treasures.', '', 'As', 'we', 'meandered,', 'we', 'spotted', 'adorable', 'squirrels', 'frolicking', 'playfully', 'among', 'the', 'branches,', 'their', 'bushy', 'tails', 'adding', 'to', 'the', 'charm', 'of', 'the', 'scene.', 'Mesmerized,', 'we', 'paused', 'to', 'admire', 'their', 'antics,', 'cherishing', 'the', 'tranquility', 'of', 'the', 'moment.', '', 'Seeking', 'respite,', 'we', 'settled', 'on', 'a', 'weathered', 'wooden', 'bench', 'beneath', 'the', 'shade', 'of', 'a', 'sprawling', 'oak.', 'A', 'gentle', 'breeze', 'rustled', 'the', 'leaves,', 'soothing'

In [174]:
list_text2.count('the')

18

In [175]:
count =[]
for i in list_text2:
  a = list_text2.count(i)
  count.append(a)

print(count)

[1, 1, 10, 1, 8, 1, 18, 1, 2, 1, 3, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 6, 1, 1, 1, 1, 2, 18, 2, 1, 10, 1, 3, 4, 1, 1, 1, 18, 1, 1, 1, 8, 1, 18, 2, 1, 1, 11, 2, 10, 1, 10, 1, 1, 1, 1, 1, 1, 18, 1, 3, 1, 1, 1, 8, 18, 1, 7, 18, 1, 1, 10, 1, 8, 1, 3, 1, 1, 18, 1, 7, 18, 1, 11, 1, 1, 10, 1, 3, 4, 1, 1, 1, 1, 18, 1, 7, 4, 1, 1, 1, 1, 1, 1, 18, 1, 1, 2, 1, 10, 1, 1, 3, 18, 1, 1, 1, 1, 1, 1, 1, 4, 1, 11, 1, 4, 1, 1, 6, 10, 1, 4, 1, 1, 7, 1, 1, 3, 4, 1, 1, 7, 1, 1, 1, 2, 18, 2, 2, 1, 1, 6, 10, 1, 1, 1, 1, 1, 3, 1, 1, 11, 3, 1, 3, 18, 2, 1, 8, 1, 1, 1, 1, 1, 18, 1, 6, 1, 7, 1, 1, 3, 1, 1, 7, 1, 6, 1, 1, 1, 1, 3, 4, 1, 2, 18, 1, 1, 1, 18, 1, 10, 1, 1, 8, 18, 1, 1, 8, 1, 1, 8, 1, 2, 2, 6, 1, 1, 1, 11, 11, 11, 11, 11, 11, 11]


In [176]:
dict_1 = dict(zip(list_text2,count))
print(dict_1)

{'Last': 1, 'weekend,': 1, 'we': 10, 'decided': 1, 'to': 8, 'explore': 1, 'the': 18, 'picturesque': 1, 'park': 2, 'nearby.': 1, 'The': 3, "park's": 2, 'lush': 1, 'beauty': 2, 'immediately': 1, 'captivated': 1, 'us': 2, 'with': 2, 'its': 2, 'tall,': 1, 'majestic': 1, 'trees': 1, 'and': 6, 'vibrant': 1, 'green': 1, 'grass.': 1, 'Excitement': 1, 'filled': 2, 'air': 2, 'as': 1, 'embarked': 1, 'on': 3, 'our': 4, 'leisurely': 1, 'stroll': 1, 'along': 1, 'winding': 1, 'pathways,': 1, 'eager': 1, 'uncover': 1, 'hidden': 1, 'treasures.': 1, '': 11, 'As': 2, 'meandered,': 1, 'spotted': 1, 'adorable': 1, 'squirrels': 1, 'frolicking': 1, 'playfully': 1, 'among': 1, 'branches,': 1, 'their': 3, 'bushy': 1, 'tails': 1, 'adding': 1, 'charm': 1, 'of': 7, 'scene.': 1, 'Mesmerized,': 1, 'paused': 1, 'admire': 1, 'antics,': 1, 'cherishing': 1, 'tranquility': 1, 'moment.': 1, 'Seeking': 1, 'respite,': 1, 'settled': 1, 'a': 4, 'weathered': 1, 'wooden': 1, 'bench': 1, 'beneath': 1, 'shade': 1, 'sprawling': 1

In [177]:
sorted_dict = sorted(dict_1.items(),key=lambda x:x[1])
print(sorted_dict)

[('Last', 1), ('weekend,', 1), ('decided', 1), ('explore', 1), ('picturesque', 1), ('nearby.', 1), ('lush', 1), ('immediately', 1), ('captivated', 1), ('tall,', 1), ('majestic', 1), ('trees', 1), ('vibrant', 1), ('green', 1), ('grass.', 1), ('Excitement', 1), ('as', 1), ('embarked', 1), ('leisurely', 1), ('stroll', 1), ('along', 1), ('winding', 1), ('pathways,', 1), ('eager', 1), ('uncover', 1), ('hidden', 1), ('treasures.', 1), ('meandered,', 1), ('spotted', 1), ('adorable', 1), ('squirrels', 1), ('frolicking', 1), ('playfully', 1), ('among', 1), ('branches,', 1), ('bushy', 1), ('tails', 1), ('adding', 1), ('charm', 1), ('scene.', 1), ('Mesmerized,', 1), ('paused', 1), ('admire', 1), ('antics,', 1), ('cherishing', 1), ('tranquility', 1), ('moment.', 1), ('Seeking', 1), ('respite,', 1), ('settled', 1), ('weathered', 1), ('wooden', 1), ('bench', 1), ('beneath', 1), ('shade', 1), ('sprawling', 1), ('oak.', 1), ('A', 1), ('gentle', 1), ('breeze', 1), ('rustled', 1), ('leaves,', 1), ('soot

In [178]:
sorted_dict2= sorted_dict[::-1]
print(sorted_dict2)

[('the', 18), ('', 11), ('we', 10), ('to', 8), ('of', 7), ('and', 6), ('a', 4), ('our', 4), ('in', 3), ('their', 3), ('on', 3), ('The', 3), ('As', 2), ('air', 2), ('filled', 2), ('its', 2), ('with', 2), ('us', 2), ('beauty', 2), ("park's", 2), ('park', 2), ('more.', 1), ('once', 1), ('serenity', 1), ('relish', 1), ('soon', 1), ('return', 1), ('promising', 1), ('park,', 1), ('farewell', 1), ('bid', 1), ('horizon,', 1), ('below', 1), ('dipped', 1), ('sun', 1), ('hearts.', 1), ('impressions', 1), ('lasting', 1), ('left', 1), ('camaraderie', 1), ('nature', 1), ('pleasures', 1), ('simple', 1), ('life.', 1), ('daily', 1), ('bustle', 1), ('hustle', 1), ('from', 1), ('escape', 1), ('enchanting', 1), ('an', 1), ('be', 1), ('proved', 1), ('day', 1), ('play.', 1), ('carefree', 1), ('at', 1), ('smile', 1), ('but', 1), ('help', 1), ("couldn't", 1), ('joy,', 1), ('infectious', 1), ('laughter', 1), ('Their', 1), ('frisbee.', 1), ('game', 1), ('lively', 1), ('engaged', 1), ('kids', 1), ('group', 1), (

In [179]:
#7. Extract Numbers from Text File

#getting only numbers(single)


a = """"In the year 2023, technology has made significant strides, and AI-powered advancements are now part of our everyday lives. People are constantly connected through various devices and platforms. The global population has reached 8.5 billion, and around 60% of the world's population has access to the internet. Data analytics plays a crucial role in decision-making, where huge datasets are processed in a matter of seconds. The average smartphone now has a processing power comparable to that of a high-end computer a decade ago. Companies are investing heavily in innovation, with billions of dollars poured into research and development. As we embrace this digital age, the opportunities seem boundless, and the reliance on technology is set to grow even further."""

numbers_list=[]
for i in a:
  try:
    j=float(i)

    if type(j)== float:
      numbers_list.append(i)
    else:
        pass
  except:
    pass

numbers_list




['2', '0', '2', '3', '8', '5', '6', '0']

In [180]:
a = """"In the year 2023, technology has made significant strides, and AI-powered advancements are now part of our everyday lives. People are constantly connected through various devices and platforms. The global population has reached 8.5 billion, and around 60% of the world's population has access to the internet. Data analytics plays a crucial role in decision-making, where huge datasets are processed in a matter of seconds. The average smartphone now has a processing power comparable to that of a high-end computer a decade ago. Companies are investing heavily in innovation, with billions of dollars poured into research and development. As we embrace this digital age, the opportunities seem boundless, and the reliance on technology is set to grow even further."""

b= a.split(" ")


In [181]:
# We can get number in a text like this to extract only number from this I write the below code

text = "In ,2020 neary 50% people of china got affected in china which is rank #1 in the world from 195 countries"
# here we have to exctract only no like 2023,50,1
# but present a = [',2023','50%','#1','195']

a= text.split(" ")
m=[]
print(a)
for  i in a:
  if l != []:
    m.append(l)


  l=[]
  for j in i:
    try:
      k=int(j)

      if type(k)== int:

        l.append(str(k))
        print(l)
    except:
      pass
print(l)
print('Extracted number list are ;',m)




['In', ',2020', 'neary', '50%', 'people', 'of', 'china', 'got', 'affected', 'in', 'china', 'which', 'is', 'rank', '#1', 'in', 'the', 'world', 'from', '195', 'countries']
['2']
['2', '0']
['2', '0', '2']
['2', '0', '2', '0']
['5']
['5', '0']
['1']
['1']
['1', '9']
['1', '9', '5']
[]
Extracted number list are ; [['2', '0', '2', '0'], ['5', '0'], ['1'], ['1', '9', '5']]


In [182]:
number_list=[]
for i in m:
  for j in range(len(i)):
    number_list.append(int(",".join(m[j]).replace(",","")))
print(number_list)
final_output= set(number_list)
print('The numbes contain in the text are :',final_output)



[2020, 50, 1, 195, 2020, 50, 2020, 2020, 50, 1]
The numbes contain in the text are : {1, 50, 195, 2020}


In [183]:
# converting [3,4] to 34
",".join(['3','4']).replace(",","")


'34'